spring.application.name=APIGateway
server.port=9001
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/campconnect